### PR TITLE
bz_GetSpikes: Fixed error on single-channel groups

### PR DESCRIPTION
**Pull request by brendonw1**
Added a simple contingency fix to allow it work on groups with only one channel

### CODE REVIEW

**Comment by DavidTingley** [comment]
Does this mean you're spike sorting a single channel?!

**Comment by brendonw1** [comment]
I mean I guess. It's for the 4 "reference" channels up high on the shank
that are hundreds of microns apart from each other.  So I usually declare
those clusters bad, but you know it's good to have this ability not break
the function.

**Comment by brendonw1** [comment]
Additionally we may start doing some things with single wires actually... now that I think of it.  No desire to isolate units but to separate E from I signals and this could be useful.

**Comment by brendonw1** [comment]
So judgey... tsk tsk

**Comment by DavidTingley** [comment]
haha just giving you a hard time :P

**Comment by brendonw1** [comment]
Ole '3po.  Actually trying to finally do that ketamine stuff.  I thought
initially that lab members would finish it but it turns out the new
ketamine projects are sufficiently different (and in mice) that it makes
sense to try to see what I can make of the animals I recorded back in old
Alexandria East.

**Pull request merged**
