### PR TITLE
SleepScore/StateEditor update

### PR DESCRIPTION
**Pull request by dlevenstein**
An update to SleepScore/StateEditor

-Reduced the number of output files - SleepScoreMetrics are now stored in SleepState.states.mat
-Separates SleepState (REM vs WAKE vs NREM) and SleepStateEpisodes (NREM packets/episodes, microarousals, etc) into two distinct structures.
-TheStateEditor can deal with non-REM/WAKE/NREM states, and prompts the user to name any unknown states.

... and other changes

As this is a pretty big update (in terms of # code lines and formatting changes) could one or two other lab members do a bug check - load some SleepState files, make sure they save correctly, etc etc, and make sure nothing is broken on your end?

### CODE REVIEW

**Comment by dlevenstein** [comment]
Merging this - I'd like to have a few people try it out in dev before it makes its way to master.

**Comment by brendonw1** [comment]
Big good changes!

**Comment by dlevenstein** [comment]
The best changes!

**Comment by brendonw1** [comment]
Should we eliminate the dev-Watson branch now?  I think we can

**Comment by dlevenstein** [comment]
2 steps ahead of you. It's gone!

**Comment by brendonw1** [comment]
Oh 2!?

Ok

**Comment by dlevenstein** [comment]
Hm.  I’m not yet sure what the second step is.

**Pull request merged**
