### PR TITLE
Get LFP from DAT

### PR DESCRIPTION
**Pull request by samamckenzie**

### CODE REVIEW

**Comment by DavidTingley** [comment]
Can we remove the .zip file, the .directory files, and the .mat files

**Comment by brendonw1** [comment]
Does this fix the errors I found?

Also I'm attaching my modifications with different I/O stuff and constants
all put at top rather than buried in code

**Comment by samamckenzie** [comment]
1.) yes you can delete .zip. the .mats in the toolbox, I have no clue about
but there won't break that lfp filter

2) I ran it on a 24hour recording and it worked.  hopefully it works on
your end

**Comment by brendonw1** [comment]
I tried this out and it works for me too.  Great

I *tried* to push some changes to the basic file bz_LFPfromDat.m on that
branch

Do you see them? I'm not sure it worked right
I'd like someone to make sure they agree with my changes
Also we need to change how "ratio" is handled.

B

**Comment by brendonw1** [comment]
Maybe I need to pull request?

**Comment by brendonw1** [comment]
I can accept Sam's pull request and then edit later if you guys prefer...
maybe that's the best git workflow?

**Comment by dlevenstein** [comment]
My "usual" workflow with merging pull requests to dev:

1) glance through the files changed tab to see if anything obvious sticks out to me in the code that should be changed (top of https://github.com/buzsakilab/buzcode/pull/173)
2a) if something looks out of whack, request that the person who opened the pull request make some changes before we merge it
2b) if nothing looks out of whack, merge pull request into dev 
3) if necessary, try out the code


In this case, David looked at the code and requested that the zip/mats be removed if possible (because there are tons of them and they may not be necessary/get in the way of seeing the new code).  Either Sam can remove them on his fork (which would update the pull request), or we can merge it into dev and one of us can delete them. I don't think we can delete them from his pull request because its on his fork.

brendon - I don't see your changes

**Comment by brendonw1** [comment]
Thank you very much

The good news is the code works nicely.
If Sam is busy, what if we do the merge first and then make edits like
remove .zip and make it more buzcode compliant?

**Comment by brendonw1** [comment]
Also, put some ideas here:
https://github.com/buzsakilab/buzcode/issues/112

**Pull request merged**
