### PR TITLE
new place field function vol1

### PR DESCRIPTION
**Pull request by AntonioFR8**

### CODE REVIEW

**Comment by dlevenstein** [comment]
addresses issue #302

**Comment by dlevenstein** [comment]
I just noticed that most of the other structs have params formatted like so:

detectorinfo: substructure with information about the detection method (fields below)
.detectorname: name of the function used for detection
.detectionparms: parameters used for detection
.detectiondate: date of detection


Should we make the structure follow this convention as well?

**Comment by dlevenstein** [comment]
Also, in general let's give one other person a chance to look through your pull request and merge - that way we get at least one additional set of eyes on code as it gets pulled in.

**Comment by AntonioFR8** [comment]
Ok, I will do like that next time.

**Pull request merged**
