### PR TITLE
fixed state editor saving

### PR DESCRIPTION
**Pull request by stephielynn921**

### CODE REVIEW

**Comment by dlevenstein** [comment]
wow great edit!

**Comment by brendonw1** [comment]
yay!  More people using TheStateEditor!

I'm just curious what problem those lines were creating?  What was it you
had to address?  I'm wondering because sometimes I put if statements like
that to handle specific problem cases - but I can't remember well enough
now so I hoped you could explain the larger context.

**Comment by dlevenstein** [comment]
something about a bug if the .states.mat hadn't yet been saved?  
@DavidTingley knows more about the edit than I do

**Comment by DavidTingley** [comment]
The lines commented out assumed that a .states.mat file already existed, even though it was part of the 'savestates' function that creates the .states.mat file

**Comment by dlevenstein** [comment]
an alternative (better?) fix could be to use bz_LoadStates, which returns [] if the states file doesn't exist.

**Comment by dlevenstein** [comment]
actually I"m glad I checked this.... thanks for bringing it up Brendon.

the modification as submitted would have written over all of the detection metadata stored in SleepState.states.mat..... because just completely ignored that an old one exists while saving.

**Comment by brendonw1** [comment]
Oh great.
But it does sound like there was a problem in another direction too.  Look
forward to a bug free and user friendly bunch of code

Hello from Freiburg Germany by the way, I'm in some sub-part of town called
vauban which is like some hippie commune.  It's nice

**Comment by dlevenstein** [comment]
Ok - I think I got it.  Brendon can you take a look whenever you get a chance (no rush :D)

**Comment by brendonw1** [comment]
Hey looks good to me Dan.  Thanks for doing that and sorry for the
confusion guys

**Pull request merged**
