### PR TITLE
SleepScoreMaster update: use Power Spectrum Slope

### PR DESCRIPTION
**Pull request by dlevenstein**
This is an update to the SleepScoreMaster algorithm for NREM detection - it adds the ability to use the slope of the (log-log) power spectrum (i.e. the 1/f exponent). So far I've found this to be more reliable in non-frontal cortex recordings and with noise, so I made it default (the previous weight method is still also available with SWWeights), but am hoping some people will try it out on their data as well.

Repull #262

### CODE REVIEW

**Comment by brendonw1** [comment]
Dumb question - I use my own fork.  How do I get this pull request into my own fork to try it?  Or do I have to use the main fork?

**Comment by dlevenstein** [comment]
Hm - let's pull it into dev and you can check it there? If you want to try it before pulling, you might be able to open a pull request from my fork

**Comment by brendonw1** [comment]
I'm fine with it in Dev.  But I'm also more cavalier than some

**Comment by brendonw1** [comment]
Oh yeah I can do from your fork to mine!.  Will do that.

**Comment by dlevenstein** [comment]
Merging. If we find PSS to be worse than SWWeights after people have tried it out, we can change the default back to SWWeights.

**Pull request merged**
