### PR TITLE
updates on the CFC functions

### PR DESCRIPTION
**Pull request by eliezyer**
Updates related to issue #292 . I haven't dealt with the name change for the functions and it is still missing a wrapper for all the functions.

### CODE REVIEW

**Comment by eliezyer** [comment]
I'm not allowed to resolve the conflicting files of this pull request

**Comment by AntonioFR8** [comment]
This looks great. 
I can't see or fix the conflicts either. Its only in bz_PhaseAmplitudeDist

**Comment by dlevenstein** [comment]
Looks good!
I can't see the conflicts on here either. I'll see what I can do when I get to lab.

**Comment by dlevenstein** [comment]
I think the problem is related to folder restructuring. Did you merge from dev into your fork before opening the pull request? Try merging from buzsakilab/dev to your fork, you should get some conflicts due to moved files, which you can resolve locally. And then we'll be able to merge the PR

**Comment by eliezyer** [comment]
I've dealt with the conflicts, it should be fine now

**Comment by dlevenstein** [comment]
Success!

**Pull request merged**
