### PR TITLE
updating bz_GetSpikes.m to load ks2 files

### PR DESCRIPTION
**Pull request by eliezyer**
related to #401

### CODE REVIEW

**Comment by brendonw1** [comment]
@valegarman @eliezyer I think this looks fine, but I'm starting to become an "old PI" and haven't been doing so much of detailed coding lately (more grants).   So I'd like it if Manuel could look too?

**Comment by brendonw1** [comment]
Maybe @AntonioFR8 can look too?

**Comment by eliezyer** [comment]
Did a small update on the new code to use the field spikeGroups instead of SpkGrps from sessionInfo structure, I see that's preferable based on the rest of the code

**Comment by valegarman** [comment]
Looks very good to me. Thanks!!

**Comment by eliezyer** [comment]
Thanks both of you for reviewing! I think you meant to merge instead of close? I merged now but revert that if needed

**Comment by brendonw1** [comment]
Thanks Eli

**Pull request merged**
