### PR TITLE
Dev to Master

### PR DESCRIPTION
**Pull request by dlevenstein**
Dev is way behind master - I'd like to get them up to date before pulling a number of changes to SleepScoring and some other things from my fork....

### CODE REVIEW

**Comment by brendonw1** [comment]
I don't have objection to this.

**Comment by DavidTingley** [comment]
warnings should be reinstated, they are annoying but necessary and in deprecated functions.

**Comment by DavidTingley** [comment]
*.exp and *.lib files should be deleted and added to .gitignore file

**Comment by DavidTingley** [comment]
TODO when I'm back next week:

-bz_getSessionInfo.m noprompts should be false by default
-TimeFromLightCycleStart.m  duplicates w/ bz_getzeitgebertime (partially)
-*.exp and *.lib files should be deleted and added to .gitignore file
-warnings should be reinstated, they are annoying but necessary and in deprecated functions.

**Pull request merged**
