### PR TITLE
Watson lab fixes

### PR DESCRIPTION
**Pull request by brendonw1**
- TheStateEditor can now output lfp/eeg data so you can view data without .lfp file present
- Fix TheStateEditor error when clicking states
- Fixes of small bugs to EventExplorer
- Bug fixes and increased efficiencies in SleepScoreMaster sub-files
- bz_GetSpikes: fixed issue of getting samples/spike
- Updating to buzcode and other bug fixes in RecordingSecondsToTimeSeconds and TimeFromLightCycleStart.

### CODE REVIEW

**Comment by dlevenstein** [comment]
Thanks Brendon - I'll get a chance to check and merge this tomorrow

**Comment by dlevenstein** [comment]
added a comment in the code... not sure how that works. But why did you get rid of the call to MergeFlagsComments in EventEplorer?... I'm pretty sure that's a necessary step to make sure your flags an comments stay aligned to the right/same event.

**Comment by brendonw1** [comment]
Hm.  I think everything I did was aimed at just making it run.  It was crashing.  But maybe I/we can dig more into that issue to get that brought back in and working.  I actually am not sure I fully understand the full dream for EventExplorer - I just wanted to look.  I can comment it back in and see what happens.  Do you want to approve this and I do that after or I retract this commit?

**Comment by dlevenstein** [comment]
It definitely needs to be there, otherwise flagged/commented events won't line up and it'll break that functionality. Possible it was crashing because it didn't know how to deal with your new start/stops.

**Comment by brendonw1** [comment]
I'm working on it now.  Can you tell me more about the comments etc?  What's the idea?

**Comment by dlevenstein** [comment]
Every event can be “flagged” (i.e. this is an event I’d like to look at/use as an example/remember/etc)
And “commented” i.e. take a note about the event. That will show up in that white box in explorer when you see that event (i.e. you could write something like “GREAT RIPPLE!” or “wtf is up with that ripple”).

You can later browse through only the events you’ve flagged/commented.

**Comment by brendonw1** [comment]
The problem is that 
exist(FO.EEbuzcodefilename,'file')
comes out as 0... because that file doesn't exist.

The file is supposed to be this
FO.EEbuzcodefilename = fullfile(basePath,[baseName,'.EventExplorer.SessionMetadata.mat']);

But I'm not sure I see where it is supposed to have been created - ie on the first run of event explorer in a particular basepath... ideas?

**Comment by dlevenstein** [comment]
Interesting.... Something may have left behind in the last update. Let me take a look in my EventExplorerDev branch and see if I forgot to merge something. That file should be saved at some point or the necessary stuff should be stored with the events.mat file

**Comment by brendonw1** [comment]
Maybe I close this pull request and re-submit when we figure that element out?  Anyway I have a lot more updates to TheStateEditor... it's significantly faster now IMO.

**Comment by dlevenstein** [comment]
Hm. Digging into EventExplorer will be a whole thing. I say merge it and let me work it out on my end - I have some old updates that I've been putting off completing, so this will be a good opportunity. Better to move forward with y'all having a working version (glad you're using it!)

**Comment by dlevenstein** [comment]
Oh, also, what's going on with FindSpindlesAndSWs? That was just a wrapper function and IMO never should have made it into buzcode. I deleted it on my branch but looks like y'all made some updates?

**Comment by brendonw1** [comment]
Want me to take it out of buzcode?

**Comment by dlevenstein** [comment]
I think so. It’s not anything I use, was supposed to be a wrapper to call SW and Spindle detection, but it doesn’t use either of the up to date methods for those and I never intended to copy it to buzcode

**Comment by brendonw1** [comment]
Do you think SW and spindle detection should remain?

**Comment by dlevenstein** [comment]
Yes of course - for SW detection use DetectSlowWaves. For spindle detection use your new detector? This particular function doesn't do either of those and was never supposed to get into buzcode - it's not anything that was ever finished for detecting anything.

**Comment by brendonw1** [comment]
I personally have (for some reason much) better luck finding spindles with
bz_FindRipples.  Maybe we remove them until further development?

**Comment by dlevenstein** [comment]
By them you mean the spindle detectors, right? DetectSlowWaves is great for SW and UP/DOWN detection, that shouldn't be deleted.

**Comment by brendonw1** [comment]
@dlevenstein Any ideas here?

**Comment by dlevenstein** [comment]
Sorry, ideas for what? (Just got back to lab from holidays)

**Comment by brendonw1** [comment]
The event explorer problems we discussed earlier in the chain and which you
said you'd look at

**Comment by dlevenstein** [comment]
Ah, sorry. I haven't gotten a chance to look at this. I'll put it on my list for tomorrow

**Comment by brendonw1** [comment]
We can just leave it for whenever.  It’s not a huge deal

**Comment by dlevenstein** [comment]
Voila! #277 should fix the issue. @brendonw1 when you get a chance could you try it out and make sure it's working with your stuff?  

We should also improve the documentation to better explain what Flags/Comments are and how to use them.

**Comment by brendonw1** [comment]
Thanks a lot.
We can try it out.

**Pull request merged**
