### PR TITLE
SleepScoreMaster update: use Power Spectrum Slope

### PR DESCRIPTION
**Pull request by dlevenstein**
This is an update to the SleepScoreMaster algorithm for NREM detection - it adds the ability to use the slope of the (log-log) power spectrum (i.e. the 1/f exponent). So far I've found this to be more reliable in non-frontal cortex recordings and with noise, so I made it default (the previous weight method is still also available with SWWeights), but am hoping some people will try it out on their data as well.

### CODE REVIEW

**Comment by raswanson** [comment]
Nice! Trying it out....today! Will let you know how it goes.

**Comment by dlevenstein** [comment]
This addresses the remainder of #227

**Comment by raswanson** [comment]
@dlevenstein  are you using this on headfixed barrel cortex data?

**Comment by dlevenstein** [comment]
Nope - have only used on home cage data

**Comment by brendonw1** [comment]
FOOOF

**Comment by brendonw1** [comment]
Shouldn't we merge this into /dev rather than /master?

**Comment by dlevenstein** [comment]
Yes. Oops. I'll reopen the PR to dev

**Pull request closed without merging**
