### PR TITLE
Tools for loading cellinfo files from multiple base paths

### PR DESCRIPTION
**Pull request by dlevenstein**
for issue #198

### CODE REVIEW

**Comment by dlevenstein** [comment]
The major change is that you can now use:

cellinfo = bz_LoadCellinfo(datasetPath,cellinfoName,'dataset',true)

to select base paths from those in datasetPath, and load a struct array where 
cellinfo(1)
cellinfo(2)
...
cellinfo(N)
are the cellinfoName structures from each of the N basePaths.

additionally, 
cellinfo = bz_LoadCellinfo(datasetPath,cellinfoName,'dataset',true,'catcall',true)
will concatenate all the cells into a single cellinfo structure, and should maintain UID from each and each cell will have the baseName it comes from.

please try it out too see if it's intuitive/buggy etc!

**Comment by dlevenstein** [comment]
@brendonw1, I think you would like to also have the ability to put in a cell array of baseNames? this will be easy to add via bz_FindBasePaths

**Comment by DavidTingley** [comment]
rather than individual functions for loading different filetypes, why not bz_Load and bz_Save that can handle all our file types?

**Comment by dlevenstein** [comment]
I think this is a great idea (but beyond the scope of this pull request) - add to/open an issue?

**Comment by dlevenstein** [comment]
I updated issue #199 to reflect the desired outcome

**Comment by dlevenstein** [comment]
As this has been stale and building up unrelated changes..... I'm going to merge it.

**Pull request merged**
