### PR TITLE
bug fix in bz_GetSpikes 

### PR DESCRIPTION
**Pull request by dlevenstein**
when loading regions from .xml if unit doesn’t exist in the units field of the xml - returns ‘noxml’

### CODE REVIEW

**Comment by DavidTingley** [comment]
@dlevenstein, can we get rid of 'WAVEFAULT' and turn the warning into an error?

**Comment by dlevenstein** [comment]
definitely! I’ll be able to do it in a bit, or you can just go ahead if you’re feeling motivated

**Comment by dlevenstein** [comment]
oh, it's in my pull request.. lol.  yeah just a sec I'll fix that and let you know

**Comment by dlevenstein** [comment]
Done

**Pull request merged**
