### PR TITLE
bz_CellMetricsSimple.m

### PR DESCRIPTION
**Pull request by AntonioFR8**

### CODE REVIEW

**Comment by brendonw1** [comment]
This looks nice.  One question: Should cellmetrics be under cellInfo.mat - in terms of type?

**Comment by AntonioFR8** [comment]
I guess thats right

**Comment by brendonw1** [comment]
I leave it to the gods of buzcode (@DavidTingley and @dlevenstein) to think about that question

**Comment by brendonw1** [comment]
You guys don't want to fit this into one of the data types we have defined?

**Comment by dlevenstein** [comment]
It doesn't look like this saves at all. Just calculate the values. If saved, it should follow the conventions of a cellinfo file 

I would recommend passing through the UIDs from the spikes structure though, just to keep things straight on which units are which.

**Pull request merged**
