### PR TITLE
add function to extract accelerometer data

### PR DESCRIPTION
**Pull request by rhuszar**
Dusting some cobwebs and beginning to address #278 

`bz_getIntanAccel.m` - process auxiliary dat file to extract/filter/downsample accelerometer data (x,y,z). Also returns norm of this vector, which can be used to readout animal motion. I haven't tested this, but I suspect this might be a more sensitive measure than EMG from LFP. Output is saved in buzcode format (accel.behavior.mat).

In the process of doing this I updated `read_Intan_RHD2000_file.m`, which loads info.rhd into matlab variables, and then moves these into the main workspace (terrible practice). I added options that allow users to specify the info.rhd file by providing a path (this avoids the GUI), as well as an option to store variables in a struct and return that. 
@valegarman In the process realized you did something like this ? I.e., `read_Intan_RHD2000_file_2.m`. Perhaps we can discuss and decide whether to merge our functions somehow..

### CODE REVIEW

**Comment by brendonw1** [comment]
There was a previous read_Intan_RHD2000_file.  It got replaced with the
other one, but I now have made it a subfunction of my function here... in
case you want it.  See line 263 and on in this file:

https://github.com/buzsakilab/buzcode/blob/dev/preprocessing/bz_DatFileMetadata.m

**Comment by samamckenzie** [comment]
Let's meet next week to coordinate output standards, this should mate with
the state editor

**Comment by AntonioFR8** [comment]
Peter also mentioned the same. 
I leave Tuesday afternoon so for me Monday after lunch would be the good time. But feel free to put another day if is good for most

**Comment by brendonw1** [comment]
This is very good.
Will mostly overlap w emg for sure.  Sometimes there are weird times Of
elevated emg tone in sleep but otherwise should be better - if you have it
in your recording.

Since we have done our best to automate state scoring, it’d be good to
automate whether or not to use accelerometer as default.  That could be a
metadata issue?  ... like we have to signify somewhere that the
accelerometer channels are valid (not blank) and are to be used.  Or we
could look at the variance of the accelerometer data if the channels are
present

**Comment by dlevenstein** [comment]
Definitely good to have it read into TheStateEditor for manual inspection, but I think we should not use accelerometer data in SleepScoreMaster.

**Comment by samamckenzie** [comment]
I think you will find that the accelerometer is more sensitive to small
arousals than the band passed median filter and more robust to probe design
(e.g number of channels, spatial separation).

That said, you have something working very well so I agree, we can default
read and wait for later tests for any implementation with auto scoring

**Comment by rhuszar** [comment]
Overall, the output is buzcode compatible, which should be what we want (although we can always improve I guess). If we want the state editor to take this as an input, I think we should make the modifications in the state editor.

**Comment by dlevenstein** [comment]
yes definitely

**Comment by brendonw1** [comment]
The stateeditor can take any mat with 1xNumseconds as an array... I think.
It should be easy or maybe already compatible.

Dan, why not use this for SleepScoreMaster?

**Comment by dlevenstein** [comment]
My thoughts:

1) SleepScoreMaster scores brain state using only brain-derived signals. Essentially all it needs is a .dat file. I see this as huge benefit, especially for older recordings in systems which there is no accelerometer data, or acceleration that was collected with any number of old methods. Yes, we could add the option for other signals, but then we have different recordings scored with a slightly different algorithm. It effectively induces standardization.

2) SleepScoreMaster has already been highly optimized/tested for a signal with the statistics of the LFP-derived EMG. There's no guarantee that the acceleration will match those statistics. For example, the EMG signal is nicely bimodal (GB things it generally reflects stabilizer muscle tone vs not), which is amazing for clustering. While the accelerometer will more likely be a continuum (range of accelerations). And will depend on the behavior of the animal.

3) Updating SSM to take this variety of signals and know what to do with them, and doing all the tests to make sure it's up to snuff and the distributions are comparable across recordings/systems/behaviors, will take a decent amount of work, and I see no reason to do it given the performance we're achieving already. As it is, from what I've seen, the EMG is one of the most reliable parts of the algorithm across regions/recordings.


That being said, if people are having issues with scoring that can be attributed to the EMG, I'd be much more inclined to do this.

**Comment by brendonw1** [comment]
These are good reasons.  I have some points below after your points

On Mon, Nov 4, 2019 at 4:08 PM Dan Levenstein <notifications@github.com>
wrote:

> My thoughts:
>
>    1.
>
>    SleepScoreMaster scores brain state using only brain-derived signals.
>    Essentially all it needs is a .dat file. I see this as huge benefit,
>    especially for older recordings in systems which there is no accelerometer
>    data, or acceleration that was collected with any number of old methods.
>    Yes, we could add the option for other signals, but then we have different
>    recordings scored with a slightly different algorithm. It effectively
>    induces standardization.
>
>
It's easy to leave EMG from LFP as default if nothing else is found...
thereby not requiring extra signals from people

>
>    1.
>
>    SleepScoreMaster has already been highly optimized/tested for a signal
>    with the statistics of the LFP-derived EMG. There's no guarantee that the
>    acceleration will match those statistics. For example, the EMG signal is
>    nicely bimodal (GB things it generally reflects stabilizer muscle tone vs
>    not), which is amazing for clustering. While the accelerometer will more
>    likely be a continuum (range of accelerations). And will depend on the
>    behavior of the animal.
>
> This is important - if it's really more bimodal.  I agree it's likely
stabilizer muscles and more correlates with basically simple
wakefulness/activity.  Maybe as more data from acceleromter comes in
someone can quickly make this comparison.

>
>    1. Updating SSM to take this variety of signals and know what to do
>    with them, and doing all the tests to make sure it's up to snuff and the
>    distributions are comparable across recordings/systems/behaviors, will take
>    a decent amount of work, and I see no reason to do it given the performance
>    we're achieving already. As it is, from what I've seen, the EMG is one of
>    the most reliable parts of the algorithm across regions/recordings.
>
> That being said, if people are having issues with scoring that can be
> attributed to the EMG, I'd be much more inclined to do this.
>
One important problem is that our EMG isn't so hot with single shank probes
(ie 64 sites) with no other recording sites in other regions.  For those
reasons accelerometer or video or similar might be helpful.

I agree let's not necessarily make it default for now, but I'd make it an
option so people can explore whether it works better for them (?)

**Pull request merged**
