### PR TITLE
Master

### PR DESCRIPTION
**Pull request by petersenpeter**

### CODE REVIEW

**Comment by dlevenstein** [comment]
Hey @petersenpeter - what does read_Intan_RHD2000_file_Peter.m do differently than [read_Intan_RHD2000_file.m](https://github.com/buzsakilab/buzcode/blob/d86f45d20882dc99a4e8f261b4425e75d7293b7f/externalPackages/read_Intan_RHD2000_file.m)? Is there change/improvement? 
If yes, could you incorporate the change into the existing function for general use? 
If not, we should avoid having personalized versions of each function.

**Comment by petersenpeter** [comment]
No it is similar to the original version of the script from Intan. The
difference is that it allows you to only provide a path, and it was a
dependent for the main function cutdatfragment. Cutdatfragment can be
rewritten to use the original intan script, after that it is not necessary
anymore.

2018-02-06 17:16 GMT-05:00 Dan Levenstein <notifications@github.com>:

**Comment by dlevenstein** [comment]
Sounds good - could you update [read_Intan_RHD2000_file.m](https://github.com/buzsakilab/buzcode/blob/d86f45d20882dc99a4e8f261b4425e75d7293b7f/externalPackages/read_Intan_RHD2000_file.m) with the improvement, change the dependency in Cutdatfragment, and delete the _Peter version, so we don't have duplicates in the repository?

**Comment by dlevenstein** [comment]
Looks good, thanks!

**Pull request merged**
