### PR TITLE
DetectSlowWaves Dependencies

### PR DESCRIPTION
**Pull request by dlevenstein**
A number of helper functions used in DetectSlowWaves which are mostly time series interval helper functions:
-SpktToSpkmat - takes spiketimes and gives a [Nt x Ncells] spike count matrix, with specified binning dt. Can have overlapping bins etc (i.e. boxcar).
-RestrctInts - takes a set of intervals and restricts to another set of intervals
-MergeSeparatedInts - Takes a set of intervals and merges any that are overlapping or within some minimum separation distance
-FindPeakInWin - dual threshold procedure, finds peaks in a signal that are larger than some threshold, with a second threshold for the surrounding window
-NormToInt - normalizes a signal to the values of that signal in some time interval. Has multiple normalization modes.

Some of these may duplicate functionality already in a buzcode function… if so, let me know and I’ll update DetectSlowWaves to use the appropriate buzcode function.

-also changed default behavior of bz_GetSpikes to ‘saveMat’=true

### CODE REVIEW

**Comment by DavidTingley** [comment]
I actually think all the bz_Get*.m functions should not have savemat=true, the defaults should always be false.  Often we only want to load a subset of data which would get loaded and then overwrite the saved file if someone forgets to reset it to false.

**Comment by DavidTingley** [comment]
both *Ints functions already exist in some form in FMAT, I forget the exact names but they're in buzcode/externalPackages/FMAToolbox/General/

findpeaks.m also can do what the peaks function does.

**Comment by dlevenstein** [comment]
alright sounds good - I made this change because yuta was running DetectSlowWaves without having previously run bz_GetSpikes, and with repeated detections it was taking forever to load spikes from clu/etc each time.

**Comment by dlevenstein** [comment]
I'll take a look at the FMA functions and see what can be replaced. 
FindPeakInWin actually adds significant functionality to findpeaks - i.e. all of the windowing things are not available in the basic find peaks, and returning the interval at which thresholds are crossed is not available. In order to use findpeaks for this functionality would have to write much of the code in the function.

**Comment by dlevenstein** [comment]
Merging pending issue #100 

also, we are up to #100 ! time for a celebration!

**Pull request merged**
