### PR TITLE
Improvements to CCG, bz_Filter

### PR DESCRIPTION
**Pull request by dlevenstein**
bz_Filter: 
can now do high pass as well as low pass filter

CCG: 
1.events don’t need to be time sorted
2. now has option to return CCG output in units of rate (events/reference event/second)

### CODE REVIEW

**Comment by dlevenstein** [comment]
why can't I request review from @samamckenzie ?

**Comment by dlevenstein** [comment]
ah - apparently you can only request review from people who are "collaborators", sent the invite to sam

**Comment by DavidTingley** [comment]
is there a reason for the change in bz_GetLFP?

**Comment by dlevenstein** [comment]
actually I didn't mean for that to be wrapped into the pull request...
I commented that out because I was tired of seeing that warning with looped LFP loads (for memory reasons)
however, I do think we should change that warning. it comes up if you do include basepath, but not basename.  I think if basepath is included and there is a .lfp file basepath/basename.lfp - there's no reason to throw a display.

**Comment by DavidTingley** [comment]
agreed, we could do a quick revamp of the getLFP function. I'll merge this for now but lets work on that later today.

**Comment by dlevenstein** [comment]
you and/or @samamckenzie should look over the changes to CCG just to make sure I didn't bung something up.... just because it's such a widely used/crucial function

**Pull request merged**
