### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by DavidTingley**
tweaks along the way, time to double check

### CODE REVIEW

**Comment by brendonw1** [comment]
This is a lot of changes!
By the way how do propose we check them?  I kinda just vote for merge and
we just see if they break... if they do we roll back.

**Comment by DavidTingley** [comment]
@brendonw1 you can check out the 'dev' branch for a while and make sure things don't break.  Though most of the changes are additions and tweaks to functions most people aren't using yet.

**Comment by brendonw1** [comment]
Are you thinking of the dev branch as a shared but not-yet-public version
of things for us to try?  I assumed dev was for just one person.
Is the idea that we get things rolling there then once we're sure we put it
out for the public?

Do you edit on that branch or on another and then send to that branch?

**Comment by DavidTingley** [comment]
Yes, collaborative development of tools we're building.  without having to worry about full functionality or breaking someone else's workflow.  Minor tweaks and new tools I put in dev first, the PR over to master.  Bugfixes should go straight into master.

**Comment by dlevenstein** [comment]
+1    The workflow I've settled into is:

-develop things on my own fork
-pull request to dev when they're ready for others to try out
-dev acts like in-lab beta (I keep my fork up-to-date with dev)
-occasional pull requests from dev to master

**Comment by brendonw1** [comment]
I see. That’s good. I didn’t realize. I’ll do the same.

**Comment by brendonw1** [comment]
Can you guys expand on the relative advantages of using your own fork
rather than a branch?

**Comment by dlevenstein** [comment]
I like having my own fork to work on, so I can do constant commits to switch between computers, or develop code over a few days, without it showing up in the collective buzcode repository. And I have a few branches on my fork for various sub-goals - i.e. one for development of EventExplorer. It can also give another level of code review.   But all of these things could be also managed with a personal branch as well.

**Comment by brendonw1** [comment]
How do you think of fork vs branch as different?

**Pull request merged**
