### PR TITLE
TheStateEditor indexing, metadata folder

### PR DESCRIPTION
**Pull request by dlevenstein**
1) TheStateEditor - modified LFP channel loading to use 0-indexing, a la buzcode standards and to make compatible with output from SleepScoreMaster
Bug fix: un-ended try/catch loop

2) Metadata - put metadata-related functions in a new folder in preprocessing
-added badchannels plugin for .xml files

### CODE REVIEW

**Comment by brendonw1** [comment]
Seems good to me.  As long as it works.  Sorry to be annoying but for me the bottom line is to ask whether it's been tested.  Did you get a chance?

Also have people talked about the idea of how to do metadata?  Or is that waiting on the NWB thing?

**Comment by dlevenstein** [comment]
I did check it. Everything loaded smoothly, but it would be good to have a second glance from someone else who knows/uses the code to see if there's anything it'll mess up or anything that will need to be changed in terms of backcompatibility that I may not have thought of.


Re: metadata, I've been away for 2 weeks so I dunno if there have been any discussions on this while I was gone. But I think it's waiting for NWB and the new programmer, as she'll be collecting and organizing datasets.

**Comment by brendonw1** [comment]
I'll look tonight and approve or comment

**Comment by dlevenstein** [comment]
thanks brendon!

**Comment by brendonw1** [comment]
Thanks Dan :)

**Comment by dlevenstein** [comment]
no problemo - one thing I'd like to update one of these days is the .eegstates.mat file...... eventually :p

**Pull request merged**
