### PR TITLE
Update bz_FindRipples output structure

### PR DESCRIPTION
**Pull request by dlevenstein**
bz_FindRipples now reflects .events.mat wiki:
-times -> timestamps
-detectorinfo structure with appropriate fields
-saves as events.mat, not event.mat

addresses Issue #73

### CODE REVIEW

**Comment by dlevenstein** [comment]
I accidentally pulled EventExplorer-dev into this branch, but reverted to the master version... 
The only actual change here is to bz_FindRipples, so just ignore the other commits. (See "files changed")

**Comment by DavidTingley** [comment]
thanks @dlevenstein!

**Comment by dlevenstein** [comment]
apologies to those who are going to have to deal with depreciated ripples.event.mat :p

**Comment by dlevenstein** [comment]
@AntonioFR8 I remember you mentioning that you had to make some updates on your local fork to bz_FindRipples... could you merge the updated code to your fork, rectify any conflicts, and submit a pull request so we can look over?

**Pull request merged**
