### PR TITLE
DL Changes to SleepScore and StateEditor

### PR DESCRIPTION
**Pull request by dlevenstein**
@brendonw1 sorry if you just got a bunch of things....... that was harder to figure out how to do than I want to admit.... the new github desktop is weird and I don't get it yet.

This pull request is just the changes that I made for SleepScoreMaster and TheStateEditor (and associated functions).

Without all the other stuff.  (though you should probably update your branch to be in line with master, also)

### CODE REVIEW

**Comment by dlevenstein** [comment]
To answer your question from the other pull request: 

What speifically are you wanting me to most be sure to check in terms of
backwards compatibilty?  Whether the old GUI can open the new files?  Or
whether the new GUI can open the old files?

I think just make sure it doesn't crash when you try to do the things you usually do... I ran it through a new recording from scratch and everything works, and tried it with one of my old SleepState.states.mat files. 
Also if you want to go through the StateEditor sections I edited and double check nothing's getting lost, that would be amazing.

**Comment by dlevenstein** [comment]
I just tried on an old SleepState.states.mat and crashed due to naming differences.... working on a fix

**Comment by dlevenstein** [comment]
Fixed.  If TheStateEditor doesn't find things in the right place when loading, it now re-calculates histsandthreshs as you originally had it (I accidentally broke this feature).

One thing I'm not sure about is if the old and new hists/thresh's are being saved. Should they be? I verified that the auto and manual ints are saved.

**Comment by brendonw1** [comment]
Not fully certain I know your question... sorry if I misconstrue it
In the past Hists and Thresh's were saved, largely for the re-scoring in
TheStateEditor (ie when you push "a").  So unless that functionality has
changed somehow, or if they are re-generated, I'd argue that they should be
saved.

**Comment by dlevenstein** [comment]
Ah, what I meant was to make sure I didn't mess up that saving.

**Comment by brendonw1** [comment]
I’ll definitely check
Thank you

**Comment by dlevenstein** [comment]
Hey @brendonw1 - I think I just fixed the MAstate loading issue. If TheStateEditor detects a "NAME"state that's not REM/NREM/WAKE during loading, will prompt the user which number state to make that (for example, would enter 2 for MA).

Can I update this branch from master, so we don't risk compatibility issues when we need to pull request these updates to master?

**Comment by brendonw1** [comment]
That's great.  I'll try it.  When you ask about update branch from
master... what do you mean?  Take it off of master and make a new branch?
I honestly don't understand git well enough to be sure I know what you're
saying, but I'll defer to your decision

**Comment by dlevenstein** [comment]
Ah - what I mean is that the "dev-watson" branch is 11 commits ahead, 144 commits behind master. 
(you can see that here: https://github.com/buzsakilab/buzcode/tree/dev-Watson or here: https://github.com/buzsakilab/buzcode/branches)

So we need to pull those commits into this branch. If we're lucky it'll be able to merge automatically. If not we'll have to rectify any differences. I'll open the pull request and lets see what happens.

**Comment by dlevenstein** [comment]
looks like the differences are in TheStateEditor (as expected). So I'm going to merge these updates into the branch before getting the update from master

**Pull request merged**
