### PR TITLE
StateEditor fix, EMGFromLFP, SpikePETH code

### PR DESCRIPTION
**Pull request by brendonw1**
- Fix to occasional graphics issue in TheStateEditor
- Made EMGFromLFP more resilient
- Added a PETH code for spikes (didn't see another one ?)

### CODE REVIEW

**Comment by dlevenstein** [comment]
looks good! do you know what the many files "changed" with "no changes" are?

**Comment by brendonw1** [comment]
Actually no!
Want me to try to remove those?... actually I had already tried to not push
those, but I guess there were some that made it through.   ?
I wasn't sure if that was typical or weird behavior by my system.  I've
already forgotten everything :)

**Comment by dlevenstein** [comment]
I remember something like that before? Maybe a windows thing? 🤷‍♂️

**Comment by brendonw1** [comment]
I'm on linux ?
Do you want me to try to get rid and re-submit for pull?

**Comment by dlevenstein** [comment]
Eh. I think the only reason it would be an issue is if it messes with permissions. If it's easy, go for it. If not, nbd

**Comment by dlevenstein** [comment]
we can always revert it if it messes anything up

**Comment by brendonw1** [comment]
I'd be surprised if there are permissions issues TBH

**Pull request merged**
