### PR TITLE
Dev watson

### PR DESCRIPTION
**Pull request by brendonw1**
Fixed some more issues of saving and statescoring in new cases that came up in the lab

### CODE REVIEW

**Comment by brendonw1** [comment]
Of note... this is my personal main working branch... so I had merged it with some other changes too.  i'm not sure how to manage that case when there are multiple pull requests outstanding but I know the code works for me and so I want to use the pull-requsted code ... I have to integrate it somewhere.  Maybe I make a new "working" branch for my lab... since master is really something else?

**Comment by dlevenstein** [comment]
Yeah, I think it's good to have a "working" (or personal dev) branch on your fork. Is there any code in this PR we shouldn't pull into buzsakilab/buzcode?

**Comment by brendonw1** [comment]
All the other stuff I synced are from other buzcode branches. Like catching
up with master and dev

**Comment by dlevenstein** [comment]
Nice. Feel free to merge it - I'm on my phone and can't from here

**Comment by brendonw1** [comment]
I merged it... check it out sometime

**Pull request merged**
