### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by DavidTingley**

### CODE REVIEW

**Comment by DavidTingley** [comment]
@eliezyer @AntonioFR8  any progress?

**Comment by eliezyer** [comment]
Yes, I'm happy with the version now. Although it would be nice if more
people could test in their dataset to see whether is not fitting my own
recordings/probes. Should I start a new pull request?

**Comment by DavidTingley** [comment]
we can test it out in the /dev branch by merging this PR.  Once other people have tried it and are happy we can PR from dev into master

**Comment by eliezyer** [comment]
Alright, the version I'm happy with I just uploaded here:
https://github.com/eliezyer/buzcode/blob/master/utilities/fileConversions/ConvertPhyKilo2Neurosuite.m

**Pull request merged**
