### PR TITLE
starting some DB stuff

### PR DESCRIPTION
**Pull request by DavidTingley**
@dlevenstein, have a look at Loadparameters (compatibility update) and dirwalk (recursion limit added). We'll also want to formalize bz_isBuzcode and  bz_isSession

@petersenpeter  I took your load scripts and put them into a more general bz_loadDB function.  bz_updateSQLFromFiles.m will eventually be the BZ->SQL update, but for now it just scans /nyuShare and gets all sessions

### CODE REVIEW

**Comment by dlevenstein** [comment]
hey @petersenpeter, want to take a look at this so we can merge it into master?

**Comment by petersenpeter** [comment]
Sorry for my late response. As I see it, there are four ways to interact with the database. 
1) download the full list of sessions or a subset thereof from the database.
2) Submit new datasets to the database
3) Update existing datasets in the database.
4) Delete datasets in the database

I would like for these four functions, to remain independent of the underlying Matlab data-structure. What I mean by this is that people not using buzcode should still be able to do all four interactions. So I suggest two solutions. Either buzcode use these general tools to interact with the database through a wrapper or a call inside a buzcode compatible function, or both set of functions exist inside the buzcode repository. I personally prefer the first option, as changes to these functions would only had to be done one place. 

I like David's addition in which the user can specify the database to connect to.

I tested the submit script on a subset of sessions, but I had not experienced the error David found for empty stings. I found the empty fields in the database (which should not have been there from the beginning) and set them to null, so that specific error does not occur again. When submitting, I suggest that we do not make 'null' value transfers for empty fields, but instead only submit fields that is not empty. In this context I want to add that mySQL does not support infinite and NaN values, so as it is now, when loading null numbers from the database, they are set to NaN in Matlab. For text fields, null values in the database are loading into Matlab as 'null'. 

Let me know if you can agree on the above and we can make the changes to the underlying files. Further if you are missing fields in the database we can add them as well.

**Comment by petersenpeter** [comment]
For the data submission, I further started working on a function that checks if the submitted data is correctly formatted for the database. It is not completely done, so I will submit it to the repository when ready.

**Comment by dlevenstein** [comment]
sounds good to me!

**Comment by DavidTingley** [comment]
@dlevenstein , is there any difference between bz_hartigansdipsigniftest.m and hartigansdipsigniftest.m?  there's also a *_ss.m sleep score variant we could get rid of

**Comment by dlevenstein** [comment]
signif test runs a significance test (calls the dip test on 500 bootstrapped distributions). They both came from the same package, we could try to merge the significance test into the basic dip test as an option, but then the dip test would have a recursive call in it somewhere.   _ss can be removed and calls can be replaced (I'll do this on the next SleepScore Update)

**Comment by dlevenstein** [comment]
merging this in so the new pulls to master don't get wrapped into it

**Pull request merged**
