### PR TITLE
Bringing dev to master.

### PR DESCRIPTION
**Pull request by dlevenstein**
everything in dev that's ahead of master is pretty well checked (the stuff we were waiting to take care of has mysteriously made it's way into master). Can't hurt to just bring it all up to date.

### CODE REVIEW

**Comment by DavidTingley** [comment]
let's revert master to `fcbc91697257100270e9c2925d42c7d30f94a4f9` first.  That is where we were prior to me messing things up.  It'll make for a nastier PR but that way everything gets checked

**Comment by dlevenstein** [comment]
ok, I'm good with that

**Comment by dlevenstein** [comment]
In other news- is there a way we can protect master? I'm sure it was just a mistaken commit somewhere from a fork that was up to date with dev and not master.

**Comment by DavidTingley** [comment]
https://help.github.com/articles/enabling-required-reviews-for-pull-requests/

**Comment by dlevenstein** [comment]
I'd like to merge this...... I think things are pretty well checked. The only thing we had discussed was removing some of that surrey toolbox, but that's nbd.

**Comment by brendonw1** [comment]
I’d just merge it
But I’m no David Tingley.

**Comment by dlevenstein** [comment]
see issue #197 - I have some recordings before spike sorting for which there are no spike groups, but yes anatomical groups.... which means that spikeGroups.nGroups became non-0 but spikeGroups.groups etc were empty. Which made errors when loading session info to add regions

**Pull request merged**
