### PR TITLE
Master

### PR DESCRIPTION
**Pull request by dlevenstein**
added the toolbox for detecting cell assemblies from Lopes-dos-santos.  uses the PCA/ICA method.

### CODE REVIEW

**Comment by dlevenstein** [comment]
great toolbox! great job adding it!

**Comment by DavidTingley** [comment]
assembly_patterns_bw.m and assembly_patterns.m?

Also there's a matlab builtin circshift.m function :P

**Comment by brendonw1** [comment]
The _bw one is my modification. Take it out.

**Comment by brendonw1** [comment]
A remote tracker branch tracks a distant repo?

**Comment by dlevenstein** [comment]
on it ;)

**Comment by dlevenstein** [comment]
circular shift in the toolbox is an unfortunately-named function used for something completely different…… how do I put it in a private folder so it doesn’t confuse anyone looking for circshift-like functionality.

**Comment by dlevenstein** [comment]
The necessary changes have been made.  Care to pull?

**Comment by brendonw1** [comment]
Literally make a folder called "private" at the level of the functions that
will call the stuff inside the folder. And put circshift in there.

**Pull request merged**
