### PR TITLE
bz_RankOrder

### PR DESCRIPTION
**Pull request by acnavasolive**
bz_RankOrder (and its complementary script bz_getSpikesRank) are now finished and ready to be tested. They are stored inside ./analysis/RankOrder/.

### CODE REVIEW

**Comment by buzsakilab** [comment]
Hey Andrea - let's hold off on pulling all these changes into master until we've had time to use them. It looks like they're already in dev.

**Comment by dlevenstein** [comment]
( Sorry, that last comment was from me - I forgot to log out of the Buzsaki lab account)

**Comment by acnavasolive** [comment]
Hi Dan!
Antonio told me to do a pull request to notify him this was ready, so he
could test the code with his analysis.
Sorry for the inconvenience!

Andrea

**Comment by dlevenstein** [comment]
The code is already in dev so he can try it out there.

**Comment by acnavasolive** [comment]
Sure!

**Comment by dlevenstein** [comment]
I bet he meant to pull request from your fork into buzsakilab/dev. Pulling from dev into master would bring in all the changes over the last few weeks, before we've all had time to test them and find any bugs/incompatibilities. In general I think it's good practice to do updates on your own fork (instead of the buzsakilab/dev branch) and then pull from your fork into dev. 

The git desktop app does have a silly thing where it starts with a branch called "dev" on your fork, that actually makes the updates on the group repository (buzsakilab), so I recommend making a personal dev branch on your fork (e.g. mine is called "DLdev"). We should definitely update the wiki to spell this out more clearly (as part of issue #349)

**Comment by acnavasolive** [comment]
Oh I see!
Again, sorry! I'm so used to use git on my own, and I haven't really been
in any group dynamics.
I can remove my contributions to dev, go to our branch, add them there, and
then make a pull request from that branch to dev. Does that make sense?
Thank you for clarifying this for me!

**Comment by dlevenstein** [comment]
No worries at all (: this is fine - everything is in dev where it belongs :p

**Comment by brendonw1** [comment]
Git... :)

**Comment by brendonw1** [comment]
I tried looking at this.  I don't understand what this code is for,
although I bet it's cool.  Can you add comments at the top about what it is
trying to accomplish?

Same with
bz_getSpikesRank.m

**Pull request closed without merging**
