### PR TITLE
New Functions for LFP analysis

### PR DESCRIPTION
**Pull request by dlevenstein**
uploading two new functions for analysis of the LFP power spectrum. Functions are operational but some work needed to meed good coding guidelines. Uploading to dev branch so Rachel can use during development.

bz_LFPPowerDist: Calculates the LFP power distribution.

bz_PowerSpectrumSlope: Calculates how the slope of the (log-log) power spectrum (i.e. the 1/f exponent) changes over time, a metric of cortical state.

Also, improvements to DetectSlowWaves input.

### CODE REVIEW

**Comment by brendonw1** [comment]
Is the slope thing inspired by the likes of Voytek?
https://github.com/voytekresearch/fooof

**Comment by dlevenstein** [comment]
yup!  note the "documentation" on line 4 %Gao, Peterson, Voytek 2016 ;)

This seems (so far) to do a good job of quantifying cortical state in William's QW data.

**Comment by brendonw1** [comment]
Cool

**Comment by DavidTingley** [comment]
maybe we should add their code as a dependency with a buzcode wrapper?  I know they're still developing a lot of things and it may be worthwhile longterm

**Pull request merged**
