### PR TITLE
EventExplorerDev to Buzcode!

### PR DESCRIPTION
**Pull request by dlevenstein**
Moving development of EventExplorer from my personal code to a buzcode branch for input

EventExplorer is a tool for looking at LFP/Spiking data around events (as saved in a baseName.eventsName.events.mat file.

Importantly, EE also has the capability to do “DetectionReview”, allowing a user to estimate hit/miss/falsealarm percentage of event detection by allowing the user to tag missed/incorrectly detected events in a small subset of windows.

This is very much in alpha/development stages… so try it out, lets squish the inevitable bugs you find and add any features anyone wants to see!

### CODE REVIEW

**Comment by dlevenstein** [comment]
what's the difference between "assigning" people and "requesting review"?

**Comment by dlevenstein** [comment]
Merged so y'all can see the code on the branch - would love to see if you can get it to load one of your events.mat files and look around etc

**Comment by brendonw1** [comment]
Hey Dan what does this do... ie in comparison to loading events into
neuroscope?

**Comment by dlevenstein** [comment]
Minor things:
-User can Flag/Comment events

Major Things:
-Detection Review - shows the user a number of random windows in the detection interval and user can mark missed/false alarm events.  
Takes like 10-20 minutes and then returns an estimated miss/FA rate which I've been using to compare/improve detection and make and ROC curve to get an appropriate sensitivity parameter to get the desired balance between over/under detection.

**Comment by dlevenstein** [comment]
These are things that would optimally get added to neuroscope, but in the meantime I wanted to get a sense of hit/miss/FA % with my slow wave detection so I made this. At that point there was no reason not to make it a general tool for doing the same for any event.mat so we can quantitatively know/report/improve/compare the quality of all our detectors. @AntonioFR8 was super interested to use it as well for ripple detection.

**Comment by brendonw1** [comment]
Oh I remember now. Sorry

**Pull request merged**
