### PR TITLE
removed old/redundant code

### PR DESCRIPTION
**Pull request by DavidTingley**
@brendonw1, let us know if there is anything in these folders you think are worth saving

### CODE REVIEW

**Comment by dlevenstein** [comment]
I think there are two questions here
1) @brendonw1, is the general tool kernel of your synapse code preserved in bz_CellClassification?
2) Do we want to preserve adrien's synaptic classification (i.e. is it good/unique enough that it's worth updating to buzcode)?

**Comment by brendonw1** [comment]
No the general kernal of my synapse code is in Sam's synapse code (I
think)... and the kernel I wrote was graphical and was a wrapper around
Adrien's instantiation of Eran's method, so no worries there.  I have no
idea what Sam did, but I think he's re-written the guts and maybe kept some
ability to click?  Love to see it sometime.

The bz_CellClassification is mostly independent and just uses waveformshape
to classify as I/E... you can then cross that with synaptic effects of a
given cell to double check/triangulate on the cell's id.

For Adrien's code, maybe we can set up an off-path area called "archive".
Or another repo? It'll be useful to have those so people can replicate
papers or just look again.  I could also put my synapse stuff here if you
want.

**Comment by DavidTingley** [comment]
@brendonw1 or @dlevenstein, can we merge this in before any conflicts come up

**Comment by dlevenstein** [comment]
So it looks like this is all Synapse detection, yet?  What is the buzcode-recommended synapse detection function?

We may want to archive this until we have that and it's been tested, etc?

**Comment by DavidTingley** [comment]
@samamckenzie, input?

**Comment by samamckenzie** [comment]
I have made some tweaks and need to repush. Then would love an external tester

**Comment by brendonw1** [comment]
Supposedly I'll be start on such analyses soonish, if no one else gets to
it before then.  Maybe in a month or so using some of William's data

**Comment by DavidTingley** [comment]
Hey guys, I've gotten an email recently from someone outside our lab that had a series of questions about synapse detection.  They found this code, rather than @samamckenzie's.  My understanding from the conversation above is that Sam's utilizes the same kernel with additional parameters and heuristics?
  I'm going to merge for now so that this doesn't happen, and we can go back to this commit if we decide we want to reintroduce any of this code (in buzcode format)

**Comment by samamckenzie** [comment]
I followed up. I need to update the code and will take care of that on
Wednesday.

This is a successful example of this project leading to better (or at least
more efficient) science.

Peace and love from SF

**Comment by dlevenstein** [comment]
@DavidTingley did you intend to delete bz_getSessionInfo with this pull request?

**Pull request merged**
