### PR TITLE
Added functions for power-weighted Spike-Phase Coupling

### PR DESCRIPTION
**Pull request by dlevenstein**
bz_GenSpikeLFPCouping takes as inputs spikes/lfp structures and calculates:
-Power-weighted spike phase coupling
-Rate-power correlation
-Mutual information between power and ISI distribution
With user-specified frequencies (Wavelet or band-pass filter).
For all cells individually, and the population as a whole (can split E/I cell populations)

bz_PowerPhaseRateMap takes as inputs spikes and a filtered LFP signal and calculates:
-rate as function of power/phase

### CODE REVIEW

**Comment by raswanson** [comment]
👍 Looks useful.

**Comment by dlevenstein** [comment]
@rhuszar here it is. 
Ideally, we update bz_PowerPhaseRatemap to return the second plot we discussed - coupling as a function of power.

@AntonioFR8 you had also expressed interest in bz_PowerPhaseRatemap... 
here is the function to calculate it.


Let me know where things aren't clear so we can update the documentation for usability

**Comment by rhuszar** [comment]
Thanks! I'll implement the change and merge when I have it working.

**Comment by AntonioFR8** [comment]
This is great Dan. I will test these functions and also finish writing and upload mines for LFP cross-frequency coupling

**Pull request merged**
