### PR TITLE
Bug Fix: bz_GetLFP

### PR DESCRIPTION
**Pull request by dlevenstein**
when using intervals

### CODE REVIEW

**Comment by dlevenstein** [comment]
On a related point... I propose we consider a change in how bz_GetLFP does multiple intervals. Nonscalar structures are a pain to deal with... (i.e. LFP(1).data, LFP(2).data, etc)

We have the LFP.timestamps field - so it wouldn't be unreasonable to put them all in the same vector just with jumps in the timestamps.

**Comment by DavidTingley** [comment]
Why do the intervals need to be double?  and I agree with you about changing multiple intervals to make it easier to access.  The problem is that it will also make it easier to make a mistake.  I can see a situation where someone ignores the timestamps field and runs analyses across the concatenated vectors without realizing there are gaps in time..

**Comment by dlevenstein** [comment]
bz_LoadBinary throws an error if intervals/starts weren't double. the better fix would be to update bz_LoadBinary

**Comment by DavidTingley** [comment]
yea we should change that to isnumeric, as seconds resolution interval sets can be (should be) stored as ints

**Comment by DavidTingley** [comment]
I'll merge this for now to fix and we can switch back after bz_loadbinary is fixed

**Comment by brendonw1** [comment]
Sorry if I'm missing something but doesn't int format restrict to
integers?  If so that's bad, right?

**Comment by dlevenstein** [comment]
yeah - interval sets should be able to be stored as integer, double, or single. so the check should be isnumeric. 

another thing is that it probably should be >=0, which is implemented with the current check, but doesn't allow int or single.

**Comment by DavidTingley** [comment]
hmm, is there a way to do multiple check with the inputParser?

**Comment by dlevenstein** [comment]
yes = can define an arbitrary check function.  
FMA half solved this by making their check functions (like @isdscalar), which has optional inputs like '>=0'. but if statement checking as opposed to inputParser.

you might also be able to put && statements in the addParameter comment?

**Comment by evilrobotxoxo** [comment]
This is not exactly germane to this conversation, but on Friday I had a
problem with the TStoolbox mergeCloseIntervals() code where one of the mex
files would crash if the intervalSets were stored as ints instead of
doubles. Funny coincidence you guys are dealing with this now. It took me a
while to figure out what was going on.

Luke

Lucas L. Sjulson, MD, PhD
Research Assistant Professor
Departments of Psychiatry and Neuroscience and Physiology
NYU School of Medicine
450 E. 29th St., 9th floor
New York, NY 10016
cell: 646-528-9672
fax: 646-501-4529

**Pull request merged**
