### PR TITLE
change fir1 and CircularMean calls

### LINKED ISSUE #130: Filter: fir1 call expects 2 output arguments and only 1 received
I am trying to test `PhaseModulation`, using
```matlab
PhaseModulation([1,2,3,4,5],linspace(0,6,5*1250),[5 10])
```
in octave and I am coming across the following error:
```
error: element number 2 undefined in return list
error: called from
    Filter at line 123 column 10
    FilterLFP at line 87 column 10
    PhaseModulation at line 85 column 13
```

The implicated line is `[b a] = fir1(order,passband/nyquist);` in 
`externalPackages/FMAToolbox/General/Filter.m` where the code expects 2 outputs from `fir1`. That function only gives one output argument in Octave's signal toolbox and in [MATLAB's most recent release](
https://www.mathworks.com/help/signal/ref/fir1.html). Is this code expecting an earlier version of this function? In the current release, [this can be fixed by setting `a = 1`](https://www.mathworks.com/help/signal/ref/filter.html)
```matlab
	case 'fir1',
		a = 1;
		if ~isempty(passband),
			if passband(1) == 0,
				b = fir1(order,passband(2)/nyquist,'low');
			else
				b = fir1(order,passband/nyquist);
			end
		else
			b = fir1(order,stopband/nyquist,'stop');
		end
```

This error can also be avoided by taking out the optional argument specifying `fir1` in `PhaseModulation` line 85:

```matlab
fil = FilterLFP(lfp,'passband',passband);
```

### LINKED ISSUE #132: bz_GetSpikes requires .spk channels even when 'getWaveforms'==false
```matlab
bz_GetSpikes(...,'getWaveforms',false)
```
shouldn't require .spk files to be in the directory. If you run it on such a basePath, it will search for .spk files (which are unused) and throw an error because it fails to find them.

### PR DESCRIPTION
**Pull request by bendichter**
fix #130 
fix #132 

In Filter, fir1 calls are changed to output only a single argument, which makes the code compatible with Octave.

I ran into a similar problem in CircularDistribution, where it looks like CircularMean should return only 2 output arguments. I'm not sure why there were 4 in the current code, but the 2 output version was commented out just beneath.

PhaseModulation now runs on my machine

### CODE REVIEW

**Comment by dlevenstein** [comment]
It seems there are two functions named CircularMean in the repository.......

[externalPackages/FMAToolbox/General/CircularMean.m](https://github.com/buzsakilab/buzcode/blob/2f3fd65ba0d4dfa9bc321f0b58cd30b70078e8e1/externalPackages/FMAToolbox/General/CircularMean.m)
and 
[analysis/lfp_spikes/PhaseModulation/CircularMean.m](https://github.com/buzsakilab/buzcode/blob/a2ed7b95e56b99f6960c9cf464d1490512a7a60a/analysis/lfp_spikes/PhaseModulation/CircularMean.m)

The function in FMAToolbox has two outputs, while the function in analysis/lfp_spikes has four.

Unfortunately.... the R value is the second output in the FMA version, but the 4th output in the lfp_spikes version. More unfortunately.... some functions call
[stats.m(i),stats.r(i)] = CircularMean(p);
and others call 
[stats.m(i),~,~,stats.r(i)] = CircularMean(p);


 I think we should depreciate the FMA version (remove the naming conflict), but also change the outputs the lfp_spikes version to match the previous version (i.e. put the r value as the 2nd output instead of the 4th), so maximally avoid fuckups.

@DavidTingley ?

**Comment by DavidTingley** [comment]
It seems we have a third version, circ_mean from the circular stats toolbox.  We should choose one version,  get ride of the rest, and update dependencies.

**Comment by DavidTingley** [comment]
after looking through this, it looks like there are a few changes we should make.  I'll pull this in so @bendichter can get things working, then I'll start a new branch where we can start updating dependencies and removing FMAT.

**Comment by bendichter** [comment]
Thanks for looking into this, guys! Oh man, I never knew I'd miss python namespaces so much!

circ_mean would be a nice solution, except it doesn't compute resultant length. It seems the lab convention is to rename analysis/lfp_spikes/PhaseModulation/CircularMean.m -> bz_CircularMean.m, which I like because it's like a poor man's namespace.

**Comment by dlevenstein** [comment]
I agree, let's keep analysis/lfp_spikes/PhaseModulation/CircularMean.m, and rename it to bz_CircularMean.   It looks to have the most functionality

**Pull request merged**
